# Dependencies
gems:        [jekyll-paginate]

# Permalinks
permalink:   /:title

# Setup
baseurl:     ""
paginate:    5
exclude:     [Gemfile, Gemfile.lock, README.md, LICENSE.md, vendor]
timezone:    Europe/London

# Site variables
title:       Clippings Geeks
tagline:     'Redesigning the design industry'
description: 'Engineering &amp; design blog sharing insights about building Clippings.com'
url:         https://clippings.github.io
github:      https://github.com/clippings
website:     https://clippings.com
websiteName: Clippings.com
